[connections.snowflake]
account = "TVLEMXB-PR39068"
user = "AniketPabrekar"
password = "Axelblaz@007"  # Make sure the key name is lowercase `password`
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
